### ISSUE TITLE
Helidon SE native image

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#1656]
Add support for new features to native image:

Ordered by priority.

- [x] WebSocket
- [x] Config HOCON support
- [x] media-jackson
- [ ] security-providers-idcs-mapper
- [x] security-providers-header
- [ ] security-providers-google-login
- [ ] Config etcd support
- [x] Config git support
- [x] security-abac-policy-el - Expression language support for security
- [x] security-abac-time - time related security 
- [x] security-providers-jwt
- [x] Reactive messaging (SE and MP)
- [ ] Kafka connector for reactive messaging

**Comment by tomas-langer** [comment]
Closing this epic.
We will handle issues with native image case by case.
