### ISSUE TITLE
Native image support for databases

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#2339]
- [x] Oracle JDBC Driver
- [x] Postgres JDBC Driver
- [x] MySQL JDBC Driver
- [ ] MariaDB JDBC Driver
- [ ] SQL Server JDBC Driver
- [ ] Derby JDBC Driver
- [ ] Liquibase DB Migration
- [ ] Neo4j Client
- [ ] Cassandra DataStax Client
- [ ] Redis Lettuce Client
- [ ] JOOQ Database Toolkit
- [ ] Elastic Search
- [x] UCP

**Comment by Tomas-Kraus** [comment]
1st step is to modify existing tests to support all those JDBC drivers:

- JPA tests
- DB Client integration tests

**Comment by Tomas-Kraus** [comment]
MS SQL Server works too but I'll add it later after PR 2442 ius merged.

**Comment by tomas-langer** [comment]
The databases we want supported are supported in Helidon 4.x.
If you need native image support for another database, we can try to see if that is feasible on case by case basis, kindly open an issue if such a need arises.
