### ISSUE TITLE
Webserver tasks for Helidon 3.0

### ISSUE THREAD

**Issue by m0mus** [helidon-io/helidon#2711]
- [x] Routing abstraction for web server #1865
- [ ] Request re-routing support #1866
- [ ] Support for dynamic matching of resources #81 (deferred to after 3.0)
- [ ] Add support for HTTP Strict Transport Security (HSTS) #932 (deferred to after 3.0)
- [x] Support for HTTP/2 Server Push #1286
- [ ] Webserver fluent path params processing #1867
- [ ] Add a robust way to get the service base URL as java.net.URL that takes care of IPv6 specialities #1891

**Comment by tomas-langer** [comment]
I am closing this epic as we are not going to implement the referenced issues in Helidon 3.
Some of the issues were fixed in 4.0
The remaining issues will be kept as enhancements
