### ISSUE TITLE
Improve testing support

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#2855]
Provide better testing support for

- unit tests
- integration tests

_Unit tests_

- [ ] Update `TestClient` to current WebServer APIs and improve usability - #2661 
- [ ] Add support for testing channel in messaging - #1855

_Integration tests_

- [ ] Improve CDI testing support, e.g. to support test containers
- [ ] Improve JPA testing support, e.g. to have a simple way to switch to a local in-memory database for testing (such as h2 with default configuration) - may be related to test containers task to support different DBs

**Comment by barchetta** [comment]
We have a new approach in Nima that we will use going forward.
