### ISSUE TITLE
Configuration metadata Epic

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#3463]
We now have annotation processor to generate metadata (#1519) for configurable components.

The annotations are now only on a few components a few steps are required to fully utilize this new feature.
 
- [x] #4325
- [x] #4326
- [ ] Use the metadata in Javadoc (maybe as a link to documentation)
- [ ] #9149
- [ ] #9157
- [ ] Consider generating an XML schema for the current dependencies + a config source capable of processing configuration generated from such a schema
- [ ] Make sure we do not duplicate the configuration documentation (should be in method javadoc + annotation). Other places should reference to the generated documentation.
- [x] #6827

**Comment by tomas-langer** [comment]
Related to #5659

**Comment by tomas-langer** [comment]
I am closing this epic. The needed tasks are either already done, or we created an issue for them. As there is only a couple of open issues, this epic is no longer required.
The tasks we did not create issues for are either obsolete, or not part of the work we want to do in forseeable future.
