### ISSUE TITLE
4.x: API Design and Níma

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#4766]
Tasks to finalize Níma (Helidon Loom based server implementation)

Prioritized:
- [x] #7339
- [x] #4868
- [x] #5425
- [x] #6338
- [x] #5388
- [x] #5411
- [x] #7244
- [x] #5659
- [x] #4869 - too big impact, can be postponed until virtual threads are GA - requires Java 21!
- [x] #5385  (#4854)
- [x] #5382
- [x] #5383
- [x] #5384
- [x] #5183
- [x] #4910
- [x] #5386 
- [x] #5390
- [x] #5389
- [x] #5391
- [x] #5393
- [x] #4394

MP switch outstanding tasks:
- [x] #5395
- [x] #5182
- [x] #5184
- [x] #5185
- [x] #5186
- [x] #5402
- [x] #5403
- [x] #5404
- [x] #5405
- [x] #5420

Production quality and other tasks - future releases
- [x] #5421
- [x] #5422
- [x] #5416
- [x] #5426
- [x] #5655
- [x] #5427
- [x] #5412

- [x] #5664
- [x] #5423
- [x] #5428
- [x] #5408
- [x] #5409
- [x] #5666
- [x] #5495
- [x] #5658

Done:
- [x] #5056
- [x] graphQL refactor to Níma (as part of #5056)
- [x] `service-common` - refactor (probably belongs to `reactive` and `microporfile` respectively) (as part of #5056)
- [x] #5060
- [x] #4873
- [x] FaultTolerance: BulkheadTest is missing (#4840)
- [x] FaultTolerance: FaultToleranceTest has disabled tests (#4855)
- [x] #4856
- [x] #4861
- [x] #4866
- [x] Use configuration aligned to Helidon MP (`server.port` instead of `nima.server.port`) - https://github.com/oracle/helidon/pull/4802
- [x] Remove old code name of Níma (Warp) from all sources - https://github.com/oracle/helidon/pull/4802
- [x] Single `SocketHttpClient` - #4794 
- [x] Single `DirectHandler` - #4782 
- [x] Move `HttpException` to common (if possible) - align handling of "internal" http exceptions that should be handled by DirectHandlers, and "user" http exceptions that should be handled by error handlers (such as 404?) - @tomas-langer 
- [x] Remove deprecated stuff from Common (align `LogConfig`, ideally to work correctly depending on which logging framework is added to classpath) #4825
