### ISSUE TITLE
Nima: Re-enable and fix tests

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#5407]
The following tests are disabled
- [x] Disabled test(s): grpc/metrics/src/test/java/io/helidon/grpc/metrics/GrpcMetricsInterceptorIT.java (#6359)
- [x] Disabled test(s): grpc/metrics/src/test/java/io/helidon/grpc/metrics/MetricsIT.java (#6359)
- [x] Disabled test(s): microprofile/cors/src/test/java/io/helidon/microprofile/cors/AdapterTest.java (#6355) 
- [x] Disabled test(s): microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestDisabledMetrics.java (#6436) 
- [x] Disabled test(s): microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestExtendedKPIMetrics.java (#6437) 
- [x] Disabled test(s): microprofile/metrics/src/test/java/io/helidon/microprofile/metrics/TestMetricsOnOwnSocket.java (#6356)
- [x] Disabled test(s): microprofile/server/src/test/java/io/helidon/microprofile/server/JerseyPropertiesTest.java (#6594)
- [x] Disabled test(s): microprofile/server/src/test/java/io/helidon/microprofile/server/ServerSseTest.java (#7626)
- [x] Disabled test(s): nima/openapi/src/test/java/io/helidon/nima/openapi/ServerTest.java (#6585)
- [x] Disabled test(s): nima/openapi/src/test/java/io/helidon/nima/openapi/TestCors.java (no longer present)
- [x] Disabled test(s): reactive/openapi/src/test/java/io/helidon/reactive/openapi/ServerModelReaderTest.java (no longer present)
- [x] Disabled test(s): reactive/openapi/src/test/java/io/helidon/reactive/openapi/TestCors.java (no longer present)
- [x] #6345
- [x] Disabled test(s): tests/functional/request-scope/src/test/java/io/helidon/tests/functional/requestscope/TenantTest.java (#7810)
- [x] Disabled test(s): tests/integration/mp-gh-3974/src/test/java/io/helidon/tests/integration/gh3974/Gh3974Test.java [removed: assertThat("Response entity should not be an empty string", response.readEntity(String.class), not(""));] (test is not disabled and runs fine)
- [x] Disabled test(s): tests/integration/mp-ws-services/src/test/java/io/helidon/tests/integration/mp/ws/services/MpServicesTest.java [testJaxrs() -> application is not available on configured socket] (#6357)
- [x] Disabled test(s): tests/integration/security/path-params/src/test/java/io/helidon/tests/integration/security/pathparams/AdminTest.java (#7832)

**Comment by ljnelson** [comment]
All tests re-enabled, removed or left alone as appropriate.
