### ISSUE TITLE
[Docs] EPIC: Updates and Revisions for 3.x  

### ISSUE THREAD

**Issue by ljamen** [helidon-io/helidon#5828]
## Environment Details
* Helidon Version: 3.1.x
* Helidon SE and Helidon MP
* JDK version: NA
* OS: NA
* Docker version (if applicable):

----------

## Problem Description
In preparation for the 4.0 release, we need to revisit our existing docs and make some improvements. 

Some of the doc improvements in 4.0 will come from [Documentation toolchain enhancements#842](https://github.com/helidon-io/helidon-build-tools/issues/842) 

**User Story**:  As a user of the Helidon documentation, I want to be able to find information quickly. The **articles** should give me basic conceptual information and pointers to Best Practices. The **guides** should help me get started quickly and link to additional information (Java docs, next steps, etc). [FAQs](https://github.com/helidon-io/helidon/wiki/FAQ)

**TOCs**: We need to address some issues with the current doc template. The basic TOC does not work for all topics. In some cases we will need to expand the TOC to include H2 and H3 headings. H4 headings should be captured in topic-level TOCs. 

**Splitting Large Articles**: Multi-chapter articles were condensed into single documents in 3.x. We need to break some of those up so that they are more 'user friendly'. 

**Content Analysis:** Identify topics that may need to be updated to include more (or less) info. Focus specifically on Introductions, Getting Started and Guides. 

## Steps to reproduce
Examples are captured in this PPT
[helidon_doc_plans.pptx](https://github.com/helidon-io/helidon/files/10387300/helidon_doc_plans.pptx)

## TOC Revisions

**MP**

- [x] https://helidon.io/docs/v3/#/mp/grpc/server @Geetha-Savithriamma
- [x] https://helidon.io/docs/v3/#/mp/lra @ljamen 
- [x] https://helidon.io/docs/v3/#/mp/config/introduction
- [x] https://helidon.io/docs/v3/#/mp/health @Geetha-Savithriamma 
- [x] https://helidon.io/docs/v3/#/mp/metrics/metrics @Geetha-Savithriamma 
- [x] https://helidon.io/docs/v3/#/mp/openapi/openapi [@ljamen Work with Tim - in progress]
- [x] https://helidon.io/docs/v3/#/mp/security/security @Geetha-Savithriamma  (WIP)
- [x] https://helidon.io/docs/v3/#/mp/tracing @ljamen 
- [x] https://helidon.io/docs/v3/#/mp/server @ljamen (addressed as part of #5925)
- [x] https://helidon.io/docs/v3/#/mp/integrations/oci @Geetha-Savithriamma (In review)

**SE**
- [x]  #5771 : https://helidon.io/docs/v3/#/se/webserver @ljamen 
- [x] https://helidon.io/docs/v3/#/se/cors @ljamen 
- [x]  https://helidon.io/docs/v3/#/se/grpc/server @Geetha-Savithriamma 
- [x] https://helidon.io/docs/v3/#/se/health @Geetha-Savithriamma 
- [x] https://helidon.io/docs/v3/#/se/metrics/metrics @Geetha-Savithriamma 
- [x] https://helidon.io/docs/v3/#/se/openapi/openapi-generator [in progress with Tim]
- [x] https://helidon.io/docs/v3/#/se/reactive-messaging @ljamen 
- [x] https://helidon.io/docs/v3/#/se/tracing @ljamen 
- [x] https://helidon.io/docs/v3/#/se/webclient @ljamen 
- [x] https://helidon.io/docs/v3/#/se/fault-tolerance @Geetha-Savithriamma 

## Split Long Topics into sub-chapters

 **MP**
- [x] https://helidon.io/docs/v3/#/mp/persistence @Geetha-Savithriamma 3.1.2 (In review)

**SE**
- [x] CORS (?) [Work with Tim]
- [x] Reactive WebServer (?) https://helidon.io/docs/v3/#/se/webserver

## Content Analysis (doc that needs work)

- [x] #5076 Alpha order for nav panel in Helidon docs (MP and SE) @Geetha-Savithriamma (approved by Dmitry)
- [x] https://helidon.io/docs/v3/#/se/security/providers @Geetha-Savithriamma 
- [x] https://helidon.io/docs/v3/#/mp/jaxrs/jaxrs-client --these topics need to be reformatted
- [x] https://helidon.io/docs/v3/#/mp/reactivemessaging/introduction

**Introduction**
For each intro, review the existing content and determine if it meets the needs of the user. IMO, these do not:

- [x] https://helidon.io/docs/v3/#/mp/aot  -- From Dmitry: this is not a useful article. GraalVM Native Image reference?
- [x] https://helidon.io/docs/v3/#/about/introduction
- [x] https://helidon.io/docs/v3/#/mp/jaxrs/application-configuration --merge into a single doc, add TOC
- [x] Add starter https://helidon.io/starter/3.1.0 to https://helidon.io/docs/v3/#/about/prerequisites
