### ISSUE TITLE
Helidon Declarative programming model

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#5889]
Helidon Declarative programming model would allow creation of Helidon SE applications using annotations, and inversion of control.
This will NOT replace Helidon SE imperative model, which we still support and plan to support for the future.

Tasks that must be done:
- [x] #9158
- [x] #6024 
- [x] #8686 (`helidon-inject` modules)
- [x] Document: how to build modules for Helidon Declarative
- [x] Document: how to build extensions/integration for Helidon Declarative
- [x] #8222 (will be fixed as a side effect of removing `helidon-inject` and introducing `helidon-service-inject`)
- [x] #7957 (dtto)
- [x] #6647 - requires test on `helidon-service-inject`
- [x] #6542 - check if relevant

Features for Helidon Declarative
- [ ] Declarative LRA annotations and runtime
- [x] OCI integration for injection of OCI SDK clients and builders
- [x] Declarative Vault integration
- [ ] Batch - investigate feature
- [x] #6748
- [x] Declarative Typed WebClient
- [x] Update of webserver to support bootstrap with service registry
- [x] Config annotations and provider
- [x] Fault tolerance annotations, interceptors, and code generation
- [x] #6852 
- [x] Helidon MP support for injecting Service Registry services
- [x] Request scope support (optional)

Nice to have (these will not block closing this epic):

- [x] #6542
