### ISSUE TITLE
4.x: OpenApi Tooling

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#5892]
Update OpenAPI tools code generator to support:

- [ ] Helidon Nima WebServer API
- [ ] Nima plus Pico API
- [ ] Generally add support for Helidon 4
   - [ ] Add any release 4-specific generation to the generators (there might not be any)
   - [ ] Verify that MP client and server work; fix any problems
   - [ ] Add 4.x SE generator; do not disrupt the 3.x SE generators
   - [ ] Regenerate the examples and replace them in our repository

**Comment by tomas-langer** [comment]
We have a new (duplicate) issue: https://github.com/helidon-io/helidon/issues/10730. As we are already working on that one, I will close this.
