### ISSUE TITLE
DOCS: Documentation to support Helidon Integration with WLS

### ISSUE THREAD

**Issue by ljamen** [helidon-io/helidon#5911]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 2.x, 3.x, 4.x
* Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Epic Scope
Doc to support  WebLogic and Helidon integration between WebLogic 12.2.1.4 and 14.1.1 with Helidon 2.x, and 3.0.
- [x] add new intro file to the 3.x integrations directory for WLS. 
- [x] add a new intro file to the 2.x integrations directory for WLS
- [ ] add a new intro file to the 4.x integrations directory for WLS (sitegen.yaml)

### JMS
- [x] #6747
- [x] #6753

//- [ ]  WLS 1412 new JMS Jakarta clients w/H3 (14.1.2 is on hold for now)
- [ ] WLS 1412 new JMS Jakarta clients w/H4 (12214 and 14.1.1 only; 14.1.2 is on hold for now)

### JAX-WS

- [x] #6754
- [x] #6755
//- [ ] WLS 1412 new jaxws-wlswss-client Jakarta Client w/H3 (14.1.2 is on hold for now)
- [ ] WLS 1412 new jaxws-wlswss-client Jakarta Client w/ H4  (12214 and 14.1.1 only; 14.1.2 is on hold for now)	

### Security/OCI

- [x] #6756
- [x] #6757
//- [ ] WLS SSO using Azure AD (as IDP) & WLS (as SP)	?	1411/12214
//- [ ] SSO across WLS 1411 and Helidon 2 on OCI using OIDC and IDCS	
//- [ ] SSO across WLS 1411 and Helidon 3 on OCI using OIDC and IDCS
//- [ ] SSO across WLS 1412 and Helidon 3 on OCI using OIDC and IDCS  (14.1.2 is on hold for now)	
- [ ] SSO across WLS 1412 and Helidon 4 on OCI using OIDC and IDCS  (14.1.2 is on hold for now)

### REST
- [x] #6758
- [x] #6759
//- [ ] Document that Helidon can call WLS webservices w/o advanced features	4.x/3.x/2.x	All
//- [x] Bidirectional REST calls between WLS 12214 w/H3	
//- [x] Bidirectional REST calls between WLS  1411 w/H2	
//- [x] Bidirectional REST calls between WLS 1411 w/H3
- [ ] Bilateral REST calls between WLS 1412  w/H3 & H4	3.x/4.x	

### MicroTX
- [x] #6762

**Comment by ljamen** [comment]
Closed by mistake.

**Comment by ljamen** [comment]
2.x issues addressed in PR #6946
3.x issues addressed in PR #6864

**Comment by ljamen** [comment]
merged #6864 for 3x
