### ISSUE TITLE
DOCS: EPIC 4.0 General Documentation

### ISSUE THREAD

**Issue by ljamen** [helidon-io/helidon#6347]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version:4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

Identify new documents needed for Helidon 4 documentation site improvement. This is not tracking the 4.x doc work associated with existing doc content. 

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**docs/about**

- [x]  Helidon Community and Support References @ljamen #7571 

- [x]  Features and Benefits of Helidon @ljamen #7571 

- [x] Helidon Documentation (new introduction page/landing page for doc) @ljamen  #7571 

- [x] Helidon Documentation Overview (site explanation) @ljamen #7571 

- [x]  Helidon Project Starter (how to use Project Starter from helidon.io) @ljamen #7571 

- [x] Introducing Helidon 4 (What's New in Helidon 4) @ljamen #7571 

- [x] Introducing Helidon (existing topic that needs to be reworked for 4.x) @ljamen #7571
