### ISSUE TITLE
DOCS: EPIC Update guides and articles for 4.x

### ISSUE THREAD

**Issue by ljamen** [helidon-io/helidon#6417]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

The guides and articles need to be updated for 4.x.
#6398 creates placeholder adoc files for each existing doc/article. Developers do not need to create the files. 

**Update - Process for updating docs for 4.x:**
When you are ready to start working on your doc issues, please let @ljamen know. I will move the issue to the In Progress column of the Docs project board. You should have the issue in your Sprint Scope. 

Where appropriate, we can work together to get the content from the 3.x branch and merged into the main branch for 4.x.  

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

**Assignments:**
First name listed is primary dev owner
Second name listed is peer reviewer for PR

### **SE Guides**              

- [x] config.adoc @arjav-desai #6445 
- [x] dbclient.adoc @romain-grecourt  (new data guide) #6450 
- [x]  gradle-build.adoc @barchetta #6471
- [x]  health.adoc @tjquinno #6451
- [x]  maven-build.adoc @barchetta #6472
- [x] metrics.adoc @tjquinno #6452
- [x] NEW migrations_3x.adoc (3 to 4) @dalexandrov #6487
- [x] security-oidc.adoc @Verdent #6454 #7730
- [x]  tracing.adoc @tomas-langer #6455 
- [x]  webclient.adoc @klustria @Verdent #6456 

### **SE Articles**

- [x] config @arjav-desai @tomas-langer #6445 
- [x] grpc @tomas-langer @klustria #6461
- [x] integrations @ljnelson  @dalexandrov @arjav-desai @trentjeff (OCI)
- [x] metrics @tjquinno #6452
- [x] openapi @tjquinno #6457
// NEW Pico intro @trentjeff #6024 PR #6572
// NEW BuilderConfig intro @trentjeff #6024 PR #6572
- [x] reactivestreams @danielkec #6458
- [x] security @Verdent #6454 #7730
- [x] NEW sse server sent events @spericas #6332
- [x] cors.adoc @tjquinno #6460 #7808
- [x] dbclient.adoc @romain-grecourt  (data.adoc) #6450
- [x] fault_tolerance.adoc @spericas @tomas-langer #6462 PR #6565 
- [x] graphql.adoc @tomas-langer #7854 
- [x] health.adoc @tjquinno #6451
- [x] observability.adoc @dalexandrov #5660 #7768 
- [x] reactive_messaging.adoc @danielkec #6459
- [x] scheduling.adoc @danielkec #6466
- [x] tracing.adoc @tomas-langer #6455 
- [x] webclient.adoc @Verdent @klustria #6456 #7812 #7847 
- [x] webserver.adoc @tomas-langer #6465 #7817
- [x] websocket.adoc @tomas-langer @spericas #6467
- [x] Logging @tomas-langer #6473 **NOTE**: Issue created in 4x to capture logging info but moved to 5x
- [x] testing @dalexandrov #6464 PR #6711

### MP Guides

- [x] config.adoc @arjav-desai @tomas-langer #6445 
- [x] graalnative.adoc  @tomas-langer #7854 #7859 
- [x] gradle-build.adoc  @barchetta  #6471
- [x] health.adoc @tjquinno  #6451
- [x] jbatch.adoc @dalexandrov (integrations) #7853
- [x] jlink-image.adoc @dalexandrov  #7855 
- [x] maven-build.adoc @barchetta #6472
- [x] metrics.adoc @tjquinno #6452
- [x] NEW migrations_3x.adoc (3 to 4) @dalexandrov #6487
- [x] overview.adoc @ljamen #6347 
- [x] security-oidc.adoc @Verdent #6454 #7730

### MP Articles

- [x] config @arjav-desai @tomas-langer  #6445
- [x] cors @tjquinno #6460 #7808
- [x] grpc @tomas-langer @klustria #6461
- [x] integrations @ljnelson  @dalexandrov @arjav-desai @trentjeff (OCI)
- [x] jax rs @spericas #6486 PR#6686
- [x] metrics @tjquinno  #6452
- [x] openapi @tjquinno #6457
- [x] reactivemessaging @danielkec #6459
- [x] reactivestreams @danielkec #6458
- [x] security @Verdent #6454 #7730
- [x] aot.adoc GraalVM @tomas-langer #7854 #7859
- [x] beanvalidation.adoc @dalexandrov 
- [x] fault_tolerance.adoc @spericas @tomas-langer #6462
- [x] graphql.adoc ? (Tim Middleton) @ljamen 
- [x] health.adoc @tjquinno  #6451
- [x] introduction @ljamen #6347 
- [x] jwt.adoc @Verdent  #6469
- [x] lra.adoc @danielkec  #6468
- [x] persistence.adoc @ljnelson #6485 #7834
- [x] restclient.adoc @danielkec #6463
- [x] scheduling.adoc @danielkec #6466
- [x] server.adoc ? @tomas-langer 
- [x] telemetry.adoc @dalexandrov #5817  #6772 
- [x] testing.adoc @dalexandrov #6464 #6711
- [x] testing-ng.adoc @dalexandrov #6464
- [x] tracing.adoc @tomas-langer #6455 
- [x] websocket.adoc @spericas @tomas-langer #6467
