### ISSUE TITLE
Nima - HTTP/2 Client - graceful connection closing

### ISSUE THREAD

**Issue by danielkec** [helidon-io/helidon#6545]
- [x] Figure how gracefully and properly close connection pool(autocloseable client? sending goaway?) #7398

- [x] Figure how to detect stale connections in the pool(using PING frame?) #7398

Tomas:
- [x] we could send pings from our idle connection handler (that times out idle connections) - shorter period, either send ping or timeout, maybe with some logic to check that we got ACK for the ping before giving the connection to anybody #7398
- [ ] add shutdown hook(?) to handle static connection caches to gracefully shut them down
