### ISSUE TITLE
Update to Jandex 3

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#6561]
## Environment Details
* Helidon Version: 4.x
* Helidon SE or Helidon MP
* JDK version:
* OS:
* Docker version (if applicable):

----------

## Problem Description
We might want to adopt the latest Jandex release.

The Jandex 3 library (as of this writing, 3.0.5 is current) is now available. Further, there is a new release of the Jandex plug-in as well, also with a different groupID. 

The effect of the library change on Helidon would be in these general areas:

1. It has some incompatible API changes as compared to Jandex Some of our code and some code in 3rd-party libraries we currently depend on use APIs removed from Jandex 3.
2.  Also the group ID changed from `org.jboss` to `io.smallrye` (although the package name remains `org.jboss.jandex`).

See https://smallrye.io/blog/jandex-3-0-0/ for a summary of the changes.

Several areas in Helidon would be affected by the Jandex library change.
- [x] Update archetypes to generate `pom.xml` files depending on Jandex 3
- [x] Update example `pom.xml` files for Jandex 3 groupID change
- [x] Update integration `pom.xml` files for Jandex 3 groupID change
- [x] Update `helidon/microprofile` `pom.xml` files for Jandex 3 groupID change
- [x] Update `microprofile/lra/jax-rs` to avoid usage of APIs removed in Jandex 3
- [x] Update tests `pom.xml` for Jandex 3 groupID change
- [x] Update Jakarta persistence API to 3.1.0 (IIRC, because of the Hibernate update)

Tracked by a separate issue:
- #7448

**Comment by barchetta** [comment]
We have worked around the Hibernate 6.1.7 dependency on Jandex 2 by excluding the dependency.  Therefore I am closing this epic as complete. I have opened #7448 to track the Hibernate upgrade seperately.
