### ISSUE TITLE
Follow up - builders, config driven

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7023]
### Milestone 1/2 issues

- [x] #7061
- [x] #7062
- [x] #7063
- [x] #7048
- [x] #7064
- [x] #7065
- [x] #7066

Nice to have/design:
- [x] #7444
- [x] #7212 

### Later issues

- [x] #7051
- [ ] There should be a way to hide the config getters from a runtime type - see https://github.com/helidon-io/helidon/pull/7008/files/fe17333a8cb4be1e903a61e0f60519f5a84741a0#diff-0548ae1d02d96dd211769a83689a753b671326950a6f6b7d7539fee160b9140f and https://github.com/helidon-io/helidon/pull/7008#discussion_r1232162905
- [x] #7443
- [x] #7026
- [ ] Enable and fix nima/webserver/webserver/src/test/java/io/helidon/nima/webserver/WebServerConfigDrivenTest.java
- [x] Pico extensions (such as config driven) should not be done as an extension of PicoProcessor, but rather using service loader, so we can add both processors to annotation processor path without causing mayhem
- [x] Prototype marker interface should also by an inner class of `Prototype` (such as `Prototype.Api`), so other types of `Prototype` is not visible from implemented classes (IDE problems)
- [x] Generated types should not use `$$` in names, as it is confusing with the classes that are created by `javac` for inner classes, maybe use `__`?
- [x] For setters of `Optional` types (class `TypeHandlerOptional`) - if the return type is an optional of a primitive type wrapper (such as `Optional<Long>`), the setters should use primitive types (and not validate for non-null)
- [ ] Write a test for `toString()` that contains a `@Confidential` property
- [x] All generated code should be compilable against APIs, and should not require runtime - this would require a bit deeper changes in Pico, as the decision how to bind would need to be delegated when binding, and not through a superclass of the generated class. It would make dependency tree much easier
- [x] Add support for a default value that would use a built type (e.g. `@ConfiguredOption(defaultEmpty=true)`), and the generated code would use something like `RetryConfig retryConfig = RetryConfig.create()`, if the type has a static method `create` without parameters, or is generated as part of the same module (currently we must have these defined as Optional, or have a custom builder interceptor to handle these types) - example in `Http2ConfigBlueprint` - where `RequestedUriDiscoveryContext` must be set using interceptor, and could be just using `create()` method.
- [x] Config metadata does not generate correct json files for blueprints (probably wrong reference to an annotation that is expected due to refactoring)
- [x] Resolve builder lines should be added to all setters (to make sure that if an argument is a builder, we call `buildPrototype` or `build` on it to resolve interceptors and validation)
- [ ] CircuitBreaker - use duration for timeouts/delays etc. (check whole FT)
- [ ] Add `@ServerTest` that supports Pico based Níma modules (after we resolve all other issues)
- [x] #7075
- [x] Config Metadata annotation processor - switch to using 'TypeName' where appropriate, use constants for type names.
- [x] Validation should (now validates required values and non-null values) also validate against allowedValues from `ConfiguredOption` - see `MyConfigBeanBlueprint` in tests
- [ ] We should have an option to explicitly add default methods that are getters as builder options, when declared on a super interface (see `HelidonOpenApiConfigBlueprint` in tests, and the disabled test
- [ ] TypeHandler - add additional default value types to support if needed
- [ ] There are a few tests that use `toString` to validate results (CustomNamedTest, MyDerivedConfigBeanTest) - there should be one dedicated test to validate `toString`, all other tests should never use `toString`
- [x] #7283
- [ ] AsyncInterceptor - do not use `hashCode` in naming, maybe switch to a counter
- [x] Use ClassModel instead - see https://github.com/helidon-io/helidon/pull/7008#discussion_r1232146932
- [x] `ConfiguredOption` support for other-than-string types - example `@ConfiguredOption("10")`
- [ ] Align naming - use `Helidon Builders` (capital letters), `Helidon Config-Driven` in all documents and javadocs when referencing these features
- [ ] Add constants (name, type) from `ProvidedUtil` to `NamedService` to have a place that explains them, and provides the keys for users.
- [ ] Consider adding the following validations - custom methods are package private (or inner class of blueprint?), builder interceptors are package private (or inner class of blueprint?) (requires a decision + enforcement + fixing existing ones)
- [ ] Design - do we need to support options of types such as List<? extends MyConfigBean>? If we come up with a use case where this is strictly better than just using `List<MyConfigBean>` we should add support for it (this make it very hard for cases where the return type is part of the same module), same for full wildcards - e.g. `Class<?>` instead of `Class<Object>` - this actually seems to be more useful, as `Class<?>` means "some class", whereas `Class<Object>` is class of object
- [ ] Make sure we use `TypeValues` constants in all annotation processors (esp. the modifiers), as we used to have the wrong, so some code may still use strings instead of constants.
- [ ] Whenever we use templates, we should move them to module package + `.templates`, and open that package (FaultTolerance, probably Http processors, and validate others), this is to own the namespace in each module, rather than opening the same package from different modules (which would probably fail in JPMS)
- [ ] check usage of string literal `@default` and refactor it to use a common constant (where appropriate). One constant is defined in `WebServer` for default socket name.
- [ ] inline uses/provides type in `nima/http2/webserver/src/main/java/module-info.java` (instead of imports)
- [ ] Design: consider adding setters for List/Set with a type of `Collection` instead of the same type as the property
- [ ] `BlueprintProcessor` - create a constant for version passed to `GeneratedAnnotationHandler`
- [x] #7071 
- [x] #7073
- [ ] HttpFeature - maybe rename socket to socketName or listenerName (and align socket/listener in Níma)
- [ ] `DependencyInfoBlueprint.elementName()` is wrong - check where used and refactor it, so it can be removed
- [ ] builder/README.md use @Singular instead of Singular
- [ ] add unit tests for FactoryMethods private static methods that look for a specific method
- [x] Prototype l. 77 - if parameter is builder, we should not do it (as in explicit builder type)
- [ ] Http2ConnectionProvider l. 40 (HelidonServiceLoader)

### Refactor existing builders
We need to go through all builders in Helidon and replace them with generated builders.
Example modules:

- common/configurable - Resource, LruCache
- nima/fault-tolerance - all fault tolerance features
- nima TLS
- nima ServerConfig/WebServer/LoomServer
 
Service loader notes

- always use duplicity of provider/interface. `spi.SomethingProvider` - used only by `ServiceLoder`, `spi.Something` - used by builders, created from `SomethingProvider`

**Comment by tomas-langer** [comment]
Most of the issues are no longer relevant. I have taken the rest as tasks when working on Helidon Declarative.
