### ISSUE TITLE
Reactive removal follow-up

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#7219]
* Helidon Version: 4.0.0-M1

---

Follow-up to #7201

- [x] https://github.com/helidon-io/helidon/issues/7204
- [x] https://github.com/helidon-io/helidon/issues/7205
- [x] https://github.com/helidon-io/helidon/issues/7203
- [x] https://github.com/helidon-io/helidon/issues/7207
- [x] 4.x fix tests in `example/openapi`
- [x] 4.x fix tests in `example/metrics`
- [x] #7240
- [x] #7241
- [x] #7220
- [x] #7224
- [x] #7225
