### ISSUE TITLE
Java 21 Follow Up

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#7221]
Required tasks to finalize as Java 21 is closer to release (or released), follow up of #6519 

- [ ] `tests/integration/jpa/pom.xml` - uncomment test modules and fix all problems
- [ ] `.mvn/jvm.config` - remove Byte Buddy experimental switch 
- [x] `.github/workflows/validate.yml` - switch to oracle release of JDK 21 when ready
- [x] Dockerfile - for all GraalVM native image docker files, fix release version and download location once available
- [ ] check `BackendTests` in Todo application, the tests are still disabled - maybe there is an embedded cassandra that works with latest Java now? If not, test it differently, or remove this
- [x] `test-packaging-native.sh` - re-enable native image packaging tests once Java 21 native image is available
- [x] #7329
