### ISSUE TITLE
Feature parity with 3.x (full custom and app types)

### ISSUE THREAD

**Issue by tvallin** [helidon-io/helidon#7268]
SE features:

Custom:

- [x] Extra - Webclient
- [x] Extra - Fault-tolerance
- [x] Extra  - CORS
- [x] Metrics - microprofile
- [x] Metrics - micrometer
- [x] Metrics - built-in
- [x] Health
- [x] Tracing - Jaeger
- [x] Tracing - Zipkin
- [x] Tracing - built-in
- [x] Packaging - Docker
- [x] Packaging - Kubernetes
- [x] Packaging - Verrazzano
- [x] Packaging - Native-image
- [x] Packaging - Jlink
- [x] Security - OIDC
- [x] Security - JWT
- [x] Security - Google
- [x] Security - Http-signature
- [x] Security - ABAC
- [x] Media - JSON-P
- [x] Media - JSON-B
- [x] Media - Jackson
- [x] Media - No JSON provider
- [x] Media - Mutlipart

Quickstart:
- [x] Quickstart

Database:
- [x] Mongodb
- [x] H2
- [x] MySQL
- [x] Oracle DB

**Comment by tvallin** [comment]
Fixed by https://github.com/helidon-io/helidon/pull/7409
