### ISSUE TITLE
3.x: Enable tests that were disabled during renaming to `jakarta` packages work

### ISSUE THREAD

**Issue by tvallin** [helidon-io/helidon#7503]
## Environment Details
* Helidon Version: 3.x
* Helidon SE and MP
* JDK version: 17
* OS:
* Docker version (if applicable):

----------

## Problem Description

Tests have to be re enabled because things can break under the radar.

## Steps to reproduce

n/a

- [ ] Example Microprofile -> ImplicitHelloWorldTest
- [ ] Example Integrations CDI pokemons -> MainTest
- [ ] Example Integrations Micronaut -> MicronautExampleTest
- [ ] Example Integration Neo-4j-mp -> MainTest
- [ ] Example Microprofile Openapi-basic -> MainTest
- [ ] Example Openapi -> MainTest
- [ ] Example TODO-app -> BackendTests
- [ ] Microprofile FaultTolerance -> RetryTest
- [ ] Tests Functional BookStore -> MainTest#basicTestMetricsHealthSEModules
- [ ] Tests Functional BookStore -> MainTest#basicTestMetricsHealthMPModules
- [ ] Tests Functional MultipleApps -> MainTest
- [ ] Tests Integration Zipkin-mp-2.2 -> ZipkinMp22Test#invokeEndPoint
