### ISSUE TITLE
Metrics follow-up items 

### ISSUE THREAD

**Issue by tjquinno** [helidon-io/helidon#7506]
Items to follow-up on in metrics for 4.x

 - [x] Changes to get the build to pass for M2
     - [x] Main metrics
         - [x] SimpleMeterRegistryTests - 1 test disabled for pipeline
         - [x] MetricsConfigSupport#isMeterEnabled - needs to do the filtering; temporarily returns true always
         - [x] ScopeConfigSupport#isMeterEnabled - needs to do the meter-level filtering
     - [x] MP metrics
         - [x] BadGaugeTest
         - [x] TestBasicPerformanceIndicators.checkMetricsVendorUrl disabled
         - [x] HelloWorldAsyncResponseWithRestRequestTest
         - [x] whole HelloWorldAsyncResponseTest
         - [x] TestMetricsOnOwnSocket whole
         - [x] TestDisabledMetrics - leaving test disabled temporarily; no-op registry not provided if metrics are disabled
         - [x] MP metrics TCK disabled
         - [x] MpFeatureTest disabled
     - [x] Other tests
         - [x] FT MetricsTest - 3 tests
         - [x] Multiport functional test MainTest - commented code
         - [x] ServerMetricsCheckIT.testHttpMetrics integration/dbclient/app
         - [x] ProtectedMetricsTest test/integration/security/gh2297
         - [x] OCI metrics OciMetricsCdiExtensionTest - count is expected = 3 but is higher perhaps because gc based metrics are gauges not counters
         - [x] webclient/tests/webclient MetricsTest 1 test disabled
         - [x] tests/native-image/mp-1
     - [x] Examples
         - [x] filtering MP MainTest
         - [x] http status count mp
