### ISSUE TITLE
4.x: dependency cleanup

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7580]
## Problem Description

We should do a final pass at dependency cleanup in 4.x. This is especially true for older dependencies. These need to be looked at and determined if they should be upgraded, removed, deprecated or otherwise addressed.

- [x] `io.dropwizard.metrics:metrics-core:4.1.2` (dbclient/metrics-hikari) #7624
- [x] `io.opentracing:opentracing-api:0.33.0` and `io.opentracing:opentracing-util:0.33.0`: we need to support opentracing because of microprofile. But it should be removed from:
    - [x] `dbclient/tracing` #7617
    - [x] `integrations/common/rest` #7618
- [x] `io.zipkin.reporter2:zipkin-sender-urlconnection:2.12.0` (tracing/providers/zipkin) #7621
- [x] #7399 
- [x] `org.eclipse.jgit:org.eclipse.jgit:5.11.1.202105131744-r` (config/git)  #7586 
- [x] `redis.clients:jedis:3.6.3` (integrations/cdi/jedis-cdi) #7619
- [x] `org.mousio:etcd4j:2.18.0`  (config/etcd) #7623
- [x] `org.jboss:jboss-transaction-spi-jakarta:7.6.1.Final` (integrations/cdi/jta-cdi) #7661
- [x] `org.jboss.classfilewriter:jboss-classfilewriter:1.2.5.Final` (microprofile/cdi) #7692
- [x] `org.jboss.logging:org.jboss.logging:3.4.2.Final` (microprofile/cdi) #7595
