### ISSUE TITLE
MicroProfile 6.1

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7805]
Support [MicroProfile 6.1](https://microprofile.io/compatible/6-1/#overview)

Update components (from 6.0 to 6.1):
- [ ] [Config 3.1](https://github.com/eclipse/microprofile-config/releases/tag/3.1)
- [ ] [Metrics 5.1.0](https://github.com/eclipse/microprofile-metrics/releases/tag/5.1.0)
- [ ] [Telemetry 1.1](https://github.com/eclipse/microprofile-telemetry/releases/tag/1.1)

**Comment by barchetta** [comment]
Duplicate of #8704
