### ISSUE TITLE
DOCS: Epic for 4.0.1 (Deferred and Bugs)

### ISSUE THREAD

**Issue by ljamen** [helidon-io/helidon#7905]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 4.0.1
* Helidon SE and Helidon MP

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Doc Issues Deferred from 4.0.1 
- [ ]  #6473  
- [ ] // NEW Pico intro @trentjeff #6024 PR #6572
- [ ] // NEW BuilderConfig intro @trentjeff #6024 PR #6572

## Bug Fixes

- [x] #7887 
- [x] #7888 
- [ ] #7885 see the Readme in GH
