### ISSUE TITLE
4.x: OpenAPI Generator

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#7943]
Update the [OpenAPI Generator](https://openapi-generator.tech/) to add support for Helidon 4:

- [x] 4.x Server MP Generator #8746 see also https://github.com/OpenAPITools/openapi-generator/issues/18261
- [x] #8879
- [x] 4.x Client MP Generator #8746 see also https://github.com/OpenAPITools/openapi-generator/issues/18261
- [x] #8880
- [x] Update documentation: 
   - [x] [SE](https://helidon.io/docs/latest/index.html#/se/openapi/openapi-generator), 
   - [x] [MP](https://helidon.io/docs/latest/index.html#/mp/openapi/openapi-generator) #8746 

### Reference
* https://github.com/OpenAPITools/openapi-generator/pull/13513
*  [Helidon and OpenAPI blog](https://medium.com/helidon/major-improvements-with-helidon-and-openapi-f76a0951508e)
* https://github.com/OpenAPITools/openapi-generator/issues/18225

**Comment by lucapf** [comment]
do we have any timelie for this to be fixed?
This is blocking the adoption of Helidon in our projects.

**Comment by barchetta** [comment]
@lucapf work has started but we do not yet have an ETA. Which of the four generators listed in the description do you require?

**Comment by lucapf** [comment]
Thank you @barchetta for your response.

Blocker, for us, is 4.X SE server generator

**Comment by barchetta** [comment]
@nagabalap7 @hrstoyanov We are aiming for end of this month.
