### ISSUE TITLE
[Epic] Opentelemetry and Helidon Tracing API in Helidon 4

### ISSUE THREAD

**Issue by dalexandrov** [helidon-io/helidon#8068]
To ensure the correct work of MP Telemetry and Helidon Tracing API, the following action items should be completed:

- [x] Do not create multiple named tracers
- [x] Identify and document the correct configuration options for `OpenTelemetry` tracing
- [x] Helidon created traces using only the last @Path element (and ignoring parent resource ones)
- [x] Identify and document the correct mechanism to obtain the `io.helidon.tracing.Tracer` instance
- [x] Support injection of `io.helidon.tracing.Tracer` in MP-based services
- [x] Spans created using `io.helidon.tracing.Tracer` API are getting attached to the same Trace as the ones created with the service code (for both Helidon 4 MP and SE based services)
