### ISSUE TITLE
MicroProfile 6.1

### ISSUE THREAD

**Issue by barchetta** [helidon-io/helidon#8704]
## Environment Details
* Helidon Version: 4
* Helidon MP

----------

## Problem Description

Support MicroProfile 6.1  ([umbrella spec](https://download.eclipse.org/microprofile/microprofile-6.1/microprofile-spec-6.1.html), [slide deck](https://docs.google.com/presentation/d/1A3Hbr-O7QFepUP5M0X2hKfqFiO1PZgnBWWhMyovu9JU/edit#slide=id.p8)) This requires upgrading the following specifications:

- [x] #8724
- [x]  [MicroProfile Fault Tolerance 4.0.2](https://download.eclipse.org/microprofile/microprofile-6.1/microprofile-spec-6.1.html#mp-fault-tolerance)
- [x] [MicroProfile Health 4.0.1](https://download.eclipse.org/microprofile/microprofile-6.1/microprofile-spec-6.1.html#mp-health-check)
- [x] [MicroProfile JWT Authentication 2.1](https://download.eclipse.org/microprofile/microprofile-6.1/microprofile-spec-6.1.html#mp-jwt-auth)
- [x]  #8004
- [x] [MicroProfile OpenAPI 3.1.1](https://download.eclipse.org/microprofile/microprofile-6.1/microprofile-spec-6.1.html#mp-open-api)
- [x] #8728
- [x] #8729
- [x] Certify [Jakarta EE 10 Core Profile](https://jakarta.ee/specifications/coreprofile/10/)

### Compatibility 

6.1 should be fully compatibly with 6.0. As stated in the 6.1 spec: "Based on MicroProfile’s time-boxed release process, this is a minor release that does not include backward incompatible changes."

### Documentation

- [x] #9095
