### ISSUE TITLE
Improve support for in-memory cache / Coherence

### ISSUE THREAD

**Issue by edbratt** [helidon-io/helidon#9005]
Improve integration support for in memory cache, such as Coherence. (Coherence CE).

- [x] helidon-io/helidon#9125
- [x] helidon-io/helidon-examples#84
- [ ] helidon-io/helidon#3118
- [ ]  #9364

(Feedback is that current Coherence Sock-shop demo is too 'turn-key' and doesn't explain the details necessary to lead customer to self-sufficient operations).
See also

- [YouTube SockShop Demo recording](https://www.youtube.com/watch?v=dbegsSXKkoI)
- [SockShop Project](https://github.com/oracle/coherence-helidon-sockshop-sample)
