### ISSUE TITLE
gRPC SE follow-up epic

### ISSUE THREAD

**Issue by spericas** [helidon-io/helidon#9138]
gRPC SE

- [ ] End-to-end example in helidon-examples
- [ ] gRPC SE security
- [ ] gRPC SE metrics 
- [ ] gRPC SE tracing
- [ ] gRPC SE health checks
