### ISSUE TITLE
gRPC MP follow-up epic

### ISSUE THREAD

**Issue by spericas** [helidon-io/helidon#9139]
### Helidon gRPC MP

- [ ] End-to-end example in helidon-examples
- [ ] gRPC MP security w/example
- [ ] gRPC MP metrics w/example
- [ ] gRPC MP tracing w/example
- [ ] gRPC MP health checks w/example
